# Generated by Django 5.2.2 on 2025-06-05 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zoho', models.CharField(max_length=100, unique=True)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Actualizado', 'Actualizado'), ('No Ubicado', 'No Ubicado')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='actualizacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('pagina_web', models.URLField(blank=True)),
                ('numero_sucursales', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_empleados', models.PositiveIntegerField(blank=True, null=True)),
                ('principales_productos', models.TextField(blank=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='actualizacion.cliente')),
            ],
        ),
    ]
