# Generated by Django 5.2.2 on 2025-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientedatos',
            name='numero_empleados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
