# Generated by Django 5.2.2 on 2025-06-07 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion', '0002_alter_clientedatos_numero_empleados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
